core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('user/', include('users.urls', namespace='users')),
]

core/learning_logs/urls.py
from django.urls import path

from .views import home, topics, topic, create_topic, edit_topic, delete_topic, \
    create_entry, edit_entry, delete_entry

app_name = 'learning_logs'
urlpatterns = [
    path('', home, name='home'),
    path('topics/', topics, name='topics'),
    path('topic/<int:pk>/', topic, name='topic'),
    path('topic/create/', create_topic, name='create_topic'),
    path('topic/<int:pk>/edit/', edit_topic, name='edit_topic'),
    path('topic/<int:pk>/delete', delete_topic, name='delete_topic'),
    path('topic/<int:pk>/entry/create/', create_entry, name='create_entry'),
    path('entry/<int:pk>/edit/', edit_entry, name='edit_entry'),
    path('entry/<int:pk>/delete', delete_entry, name='delete_entry'),
]

core/users/urls.py
from django.urls import path

from .views import signup, sign_in, log_out

app_name = 'users'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('sign_in/', sign_in, name='sign_in'),
    path('logout/', log_out, name='logout'),
]

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap4 %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand text-primary" href="{% url 'learning_logs:home' %}">
            Learning Logs
        </a>
    <ul class="nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}" >
                Topics
            </a>
        </li>
    </ul>
    <ul class="nav ml-auto">
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">
                    Logout
                </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">
                    Signup
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:sign_in' %}">
                    Signin
                </a>
            </li>
        {% endif %}
    </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        {% block content %}
            <div class="col mt-5">
                <div class="jumbotron">
                    <h1 class="display-4">Greetings!</h1>
                    <p class="lead">
                        <a href="{% url 'users:signup' %}">Register an account</a>
                        to make your own Learning Log, and list the topics you're learning about.
                    </p>
                    <hr class="my-4">
                    <p>
                        Whenever you learn something new about a topic, make an entry
                        summarizing what you've learned.
                    </p>
                    <a class="btn btn-primary btn-lg" href="{% url 'users:signup' %}" role="button">Track your learning</a>
                </div>
            </div>
        {% endblock %}
    </div>
</div>
</body>
</html>