core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('user/', include('users.urls', namespace='users')),
]

core/learning_logs/urls.py
from django.urls import path

from .views import home, topics, topic, create_topic, edit_topic, delete_topic, \
    create_entry, edit_entry, delete_entry

app_name = 'learning_logs'
urlpatterns = [
    path('', home, name='home'),
    path('topics/', topics, name='topics'),
    path('topic/<int:pk>/', topic, name='topic'),
    path('topic/create/', create_topic, name='create_topic'),
    path('topic/<int:pk>/edit/', edit_topic, name='edit_topic'),
    path('topic/<int:pk>/delete', delete_topic, name='delete_topic'),
    path('topic/<int:pk>/entry/create/', create_entry, name='create_entry'),
    path('entry/<int:pk>/edit/', edit_entry, name='edit_entry'),
    path('entry/<int:pk>/delete', delete_entry, name='delete_entry'),
]

core/learning_logs/models.py
from django.db import models

from users.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')

    def __str__(self):
        return self.text[:25] + '...'


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='entries')
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:25] + '...'

core/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    class Meta:
        model = Topic
        fields = ['text']


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'autofocus': True, 'class': 'form-control'})}

core/learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def home(request):
    return render(request, 'learning_logs/home.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    entries = topic.entries.order_by('-date')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def create_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            created_topic = form.save(commit=False)
            created_topic.owner = request.user
            created_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/crud/create_topic.html', context)


def edit_topic(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/crud/edit_topic.html', context)


@login_required
def delete_topic(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    if request.method == 'POST':
        topic.delete()
        return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'topic': topic}
    return render(request, 'learning_logs/crud/delete_topic.html', context)


@login_required
def create_entry(request, pk):
    topic = get_object_or_404(Topic, id=pk)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            created_entry = form.save(commit=False)
            created_entry.topic = topic
            created_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[pk]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/crud/create_entry.html', context)


@login_required
def edit_entry(request, pk):
    entry = get_object_or_404(Entry, id=pk)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/crud/edit_entry.html', context)


@login_required
def delete_entry(request, pk):
    entry = get_object_or_404(Entry, id=pk)
    if request.method == 'POST':
        entry.delete()
        return HttpResponseRedirect(reverse('learning_logs:topic', args=[entry.topic.id]))
    context = {'entry': entry}
    return render(request, 'learning_logs/crud/delete_entry.html', context)

core/learning_logs/templates/learning_logs/home.html
{% extends 'base.html' %}

core/learning_logs/templates/learning_logs/topic.html
{% extends 'base.html' %}
{% block content %}
<div class="col m-5">
    <h2>{{ topic }}</h2>
    <hr>
    <a href="{% url 'learning_logs:create_entry' topic.id %}">Add new entry</a>
    <h5>Entries:</h5>
        {% for entry in entries %}
            <div class="card mb-3">
                <h5 class="card-header">{{ entry.date}}</h5>
                <div class="card-body">
                    <p class="card-text">{{ entry.text|linebreaks }}</p>
                    <a class="btn btn-outline-primary btn-sm"
                       href="{% url 'learning_logs:edit_entry' entry.id %}">
                        Edit
                    </a>
                    <a class="btn btn-outline-danger btn-sm"
                       href="{% url 'learning_logs:delete_entry' entry.id %}">
                        Delete
                    </a>
                </div>
            </div>
        {% empty %}
            <p class="text-warning">There are no entries for this topic yet.</p>
        {% endfor %}
</div>
{% endblock %}

core/learning_logs/templates/learning_logs/topics.html
{% extends 'base.html' %}

{% block content %}
<div class="col mt-3">
    <div class="list-group">
        <div class="list-group-item">
            <h1>Topics</h1>
            <a href="{% url 'learning_logs:create_topic' %}"> Add new topic </a>
        </div>
        {% for topic in topics %}
            <a class="list-group-item list-group-item-action list-group-item-primary"
               href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}
            </a>
            <p>
                <a class="btn btn-sm btn-light text-primary"
                   href="{% url 'learning_logs:edit_topic' topic.id %}">
                    Edit
                </a>
                <a class="btn btn-sm btn-light text-danger"
                   href="{% url 'learning_logs:delete_topic' topic.id %}">
                    Delete
                </a>
            </p>
        {% empty %}
            <p class="list-group-item list-group-item-warning">No topics have been added yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}